import { ThemeSchema } from "../themePresets";

export const restaurantTheme: ThemeSchema = {
  id: "restaurant-modern",
  name: "Modern Restaurant",
  description: "Warm, inviting design perfect for restaurants and cafes",
  version: "2.0.0",
  darkMode: true,
  colors: {
    light: {
      primary: "#d97706", // Warm amber
      primaryForeground: "#ffffff",
      secondary: "#92400e", // Deep brown
      secondaryForeground: "#ffffff",
      accent: "#ea580c", // Orange accent
      accentForeground: "#ffffff",
      background: "#fffbf5", // Warm cream
      foreground: "#451a03",
      card: "#ffffff",
      cardForeground: "#451a03",
      popover: "#ffffff",
      popoverForeground: "#451a03",
      muted: "#fef3c7", // Light amber
      mutedForeground: "#78350f",
      border: "#fed7aa",
      input: "#fef3c7",
      ring: "#f59e0b",
      destructive: "#dc2626",
      destructiveForeground: "#ffffff",
      success: "#059669",
      successForeground: "#ffffff",
      warning: "#f59e0b",
      warningForeground: "#ffffff",
      info: "#3b82f6",
      infoForeground: "#ffffff",
    },
    dark: {
      primary: "#fbbf24", // Bright amber
      primaryForeground: "#451a03",
      secondary: "#f59e0b",
      secondaryForeground: "#451a03",
      accent: "#fb923c",
      accentForeground: "#451a03",
      background: "#1a0f00", // Deep warm black
      foreground: "#fef3c7",
      card: "#2a1810",
      cardForeground: "#fef3c7",
      popover: "#2a1810",
      popoverForeground: "#fef3c7",
      muted: "#451a03",
      mutedForeground: "#fde68a",
      border: "#78350f",
      input: "#451a03",
      ring: "#fbbf24",
      destructive: "#ef4444",
      destructiveForeground: "#ffffff",
      success: "#10b981",
      successForeground: "#ffffff",
      warning: "#f59e0b",
      warningForeground: "#ffffff",
      info: "#60a5fa",
      infoForeground: "#ffffff",
    },
  },
  typography: {
    fontFamilyBase: "Lora, Georgia, serif",
    fontFamilyHeading: "Playfair Display, Georgia, serif",
    fontFamilyMonospace: "Menlo, Monaco, Consolas, monospace",
    fontSize: {
      xs: "0.75rem",
      sm: "0.875rem",
      base: "1rem",
      lg: "1.125rem",
      xl: "1.25rem",
      xl2: "1.5rem",
      xl3: "1.875rem",
      xl4: "2.25rem",
      xl5: "3rem",
      xl6: "3.75rem",
      xl7: "4.5rem",
      xl8: "6rem",
      xl9: "8rem",
    },
    fontWeight: {
      thin: 100,
      extralight: 200,
      light: 300,
      normal: 400,
      medium: 500,
      semibold: 600,
      bold: 700,
      extrabold: 800,
      black: 900,
    },
    lineHeight: {
      none: "1",
      tight: "1.25",
      snug: "1.375",
      normal: "1.5",
      relaxed: "1.625",
      loose: "2",
    },
    letterSpacing: {
      tighter: "-0.05em",
      tight: "-0.025em",
      normal: "0em",
      wide: "0.025em",
      wider: "0.05em",
      widest: "0.1em",
    },
  },
  spacing: {
    spacing: {
      s0: "0px",
      s0_5: "0.125rem",
      s1: "0.25rem",
      s1_5: "0.375rem",
      s2: "0.5rem",
      s2_5: "0.625rem",
      s3: "0.75rem",
      s3_5: "0.875rem",
      s4: "1rem",
      s5: "1.25rem",
      s6: "1.5rem",
      s7: "1.75rem",
      s8: "2rem",
      s9: "2.25rem",
      s10: "2.5rem",
      s11: "2.75rem",
      s12: "3rem",
      s14: "3.5rem",
      s16: "4rem",
      s20: "5rem",
      s24: "6rem",
      s28: "7rem",
      s32: "8rem",
      s36: "9rem",
      s40: "10rem",
      s44: "11rem",
      s48: "12rem",
      s52: "13rem",
      s56: "14rem",
      s60: "15rem",
      s64: "16rem",
      s72: "18rem",
      s80: "20rem",
      s96: "24rem",
    },
    container: {
      sm: "640px",
      md: "768px",
      lg: "1024px",
      xl: "1280px",
      xl2: "1536px",
      full: "100%",
    },
    sectionSpacing: {
      none: "0",
      sm: "2rem",
      md: "4rem",
      lg: "6rem",
      xl: "8rem",
      xl2: "10rem",
    },
  },
  effects: {
    borderRadius: {
      none: "0",
      sm: "0.125rem",
      base: "0.5rem",
      md: "0.75rem",
      lg: "1rem",
      xl: "1.5rem",
      xl2: "2rem",
      xl3: "3rem",
      full: "9999px",
    },
    boxShadow: {
      none: "none",
      sm: "0 1px 2px 0 rgb(0 0 0 / 0.05)",
      base: "0 1px 3px 0 rgb(0 0 0 / 0.1), 0 1px 2px -1px rgb(0 0 0 / 0.1)",
      md: "0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)",
      lg: "0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)",
      xl: "0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.1)",
      xl2: "0 25px 50px -12px rgb(0 0 0 / 0.25)",
      inner: "inset 0 2px 4px 0 rgb(0 0 0 / 0.05)",
    },
    transition: {
      none: "none",
      all: "all 150ms cubic-bezier(0.4, 0, 0.2, 1)",
      colors:
        "background-color, border-color, color, fill, stroke 150ms cubic-bezier(0.4, 0, 0.2, 1)",
      opacity: "opacity 150ms cubic-bezier(0.4, 0, 0.2, 1)",
      shadow: "box-shadow 150ms cubic-bezier(0.4, 0, 0.2, 1)",
      transform: "transform 150ms cubic-bezier(0.4, 0, 0.2, 1)",
    },
    animation: {
      none: "none",
      spin: "spin 1s linear infinite",
      ping: "ping 1s cubic-bezier(0, 0, 0.2, 1) infinite",
      pulse: "pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite",
      bounce: "bounce 1s infinite",
      fadeIn: "fadeIn 0.5s ease-out",
      fadeOut: "fadeOut 0.5s ease-in",
      slideUp: "slideUp 0.3s ease-out",
      slideDown: "slideDown 0.3s ease-out",
    },
  },
  components: {
    button: {
      variants: {
        primary: {
          base: "bg-primary text-primary-foreground shadow-md",
          hover: "bg-primary/90 shadow-lg",
          active: "bg-primary/80",
          disabled: "opacity-50 cursor-not-allowed",
        },
        secondary: {
          base: "bg-secondary text-secondary-foreground",
          hover: "bg-secondary/90",
          active: "bg-secondary/80",
          disabled: "opacity-50 cursor-not-allowed",
        },
        outline: {
          base: "border-2 border-primary bg-transparent text-primary",
          hover: "bg-primary text-primary-foreground",
          active: "bg-primary/90",
          disabled: "opacity-50 cursor-not-allowed",
        },
        ghost: {
          base: "hover:bg-muted",
          hover: "bg-muted",
          active: "bg-muted/80",
          disabled: "opacity-50 cursor-not-allowed",
        },
      },
      sizes: {
        sm: {
          padding: "0.5rem 1rem",
          fontSize: "0.875rem",
          height: "2.5rem",
        },
        md: {
          padding: "0.75rem 1.5rem",
          fontSize: "1rem",
          height: "3rem",
        },
        lg: {
          padding: "1rem 2rem",
          fontSize: "1.125rem",
          height: "3.5rem",
        },
      },
      borderRadius: "0.75rem",
      fontWeight: "600",
      transition: "all 200ms cubic-bezier(0.4, 0, 0.2, 1)",
    },
    link: {
      base: "text-accent font-medium",
      hover: "text-accent/80 underline",
      visited: "text-accent/70",
      underline: false,
      transition: "all 200ms cubic-bezier(0.4, 0, 0.2, 1)",
    },
    card: {
      borderRadius: "1rem",
      boxShadow:
        "0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)",
      padding: "1.5rem",
      borderWidth: "0",
      borderColor: "transparent",
    },
    input: {
      borderRadius: "0.5rem",
      borderWidth: "2px",
      borderColor: "border",
      focusBorderColor: "ring",
      padding: "0.625rem 0.875rem",
      fontSize: "1rem",
      transition: "all 200ms cubic-bezier(0.4, 0, 0.2, 1)",
    },
  },
  sections: {
    hero: {
      minHeight: "70vh",
      padding: "4rem 2rem",
      textAlign: "center",
      overlayOpacity: 0.4,
    },
    about: {
      padding: "5rem 2rem",
      maxWidth: "64rem",
      textAlign: "center",
    },
    gallery: {
      padding: "5rem 2rem",
      gridCols: 3,
      gap: "1.5rem",
      aspectRatio: "square",
    },
    contact: {
      padding: "5rem 2rem",
      layout: "split",
      formWidth: "28rem",
    },
    reviews: {
      padding: "5rem 2rem",
      layout: "grid",
      itemsPerRow: 2,
    },
  },
};
