import { ThemeSchema } from "./themePresets";

// Restaurant Theme - Warm and Inviting
export const restaurantTheme: ThemeSchema = {
  id: "restaurant-modern",
  name: "Modern Restaurant",
  description: "Warm, inviting design perfect for restaurants and cafes",
  version: "2.0.0",
  darkMode: true,
  colors: {
    light: {
      primary: "#d97706", // Warm amber
      primaryForeground: "#ffffff",
      secondary: "#92400e", // Deep brown
      secondaryForeground: "#ffffff",
      accent: "#ea580c", // Orange accent
      accentForeground: "#ffffff",
      background: "#fffbf5", // Warm cream
      foreground: "#451a03",
      card: "#ffffff",
      cardForeground: "#451a03",
      popover: "#ffffff",
      popoverForeground: "#451a03",
      muted: "#fef3c7", // Light amber
      mutedForeground: "#78350f",
      border: "#fed7aa",
      input: "#fef3c7",
      ring: "#f59e0b",
      destructive: "#dc2626",
      destructiveForeground: "#ffffff",
      success: "#059669",
      successForeground: "#ffffff",
      warning: "#f59e0b",
      warningForeground: "#ffffff",
      info: "#3b82f6",
      infoForeground: "#ffffff",
    },
    dark: {
      primary: "#fbbf24", // Bright amber
      primaryForeground: "#451a03",
      secondary: "#f59e0b",
      secondaryForeground: "#451a03",
      accent: "#fb923c",
      accentForeground: "#451a03",
      background: "#1a0f00", // Deep warm black
      foreground: "#fef3c7",
      card: "#2a1810",
      cardForeground: "#fef3c7",
      popover: "#2a1810",
      popoverForeground: "#fef3c7",
      muted: "#451a03",
      mutedForeground: "#fde68a",
      border: "#78350f",
      input: "#451a03",
      ring: "#fbbf24",
      destructive: "#ef4444",
      destructiveForeground: "#ffffff",
      success: "#10b981",
      successForeground: "#ffffff",
      warning: "#f59e0b",
      warningForeground: "#ffffff",
      info: "#60a5fa",
      infoForeground: "#ffffff",
    },
  },
  typography: {
    fontFamilyBase: "Lora, Georgia, serif",
    fontFamilyHeading: "Playfair Display, Georgia, serif",
    fontFamilyMonospace: "Menlo, Monaco, Consolas, monospace",
    fontSize: {
      xs: "0.75rem",
      sm: "0.875rem",
      base: "1rem",
      lg: "1.125rem",
      xl: "1.25rem",
      xl2: "1.5rem",
      xl3: "1.875rem",
      xl4: "2.25rem",
      xl5: "3rem",
      xl6: "3.75rem",
      xl7: "4.5rem",
      xl8: "6rem",
      xl9: "8rem",
    },
    fontWeight: {
      thin: 100,
      extralight: 200,
      light: 300,
      normal: 400,
      medium: 500,
      semibold: 600,
      bold: 700,
      extrabold: 800,
      black: 900,
    },
    lineHeight: {
      none: "1",
      tight: "1.25",
      snug: "1.375",
      normal: "1.5",
      relaxed: "1.625",
      loose: "2",
    },
    letterSpacing: {
      tighter: "-0.05em",
      tight: "-0.025em",
      normal: "0em",
      wide: "0.025em",
      wider: "0.05em",
      widest: "0.1em",
    },
  },
  spacing: {
    spacing: {
      s0: "0px",
      s0_5: "0.125rem",
      s1: "0.25rem",
      s1_5: "0.375rem",
      s2: "0.5rem",
      s2_5: "0.625rem",
      s3: "0.75rem",
      s3_5: "0.875rem",
      s4: "1rem",
      s5: "1.25rem",
      s6: "1.5rem",
      s7: "1.75rem",
      s8: "2rem",
      s9: "2.25rem",
      s10: "2.5rem",
      s11: "2.75rem",
      s12: "3rem",
      s14: "3.5rem",
      s16: "4rem",
      s20: "5rem",
      s24: "6rem",
      s28: "7rem",
      s32: "8rem",
      s36: "9rem",
      s40: "10rem",
      s44: "11rem",
      s48: "12rem",
      s52: "13rem",
      s56: "14rem",
      s60: "15rem",
      s64: "16rem",
      s72: "18rem",
      s80: "20rem",
      s96: "24rem",
    },
    container: {
      sm: "640px",
      md: "768px",
      lg: "1024px",
      xl: "1280px",
      xl2: "1536px",
      full: "100%",
    },
    sectionSpacing: {
      none: "0",
      sm: "2rem",
      md: "4rem",
      lg: "6rem",
      xl: "8rem",
      xl2: "10rem",
    },
  },
  effects: {
    borderRadius: {
      none: "0",
      sm: "0.125rem",
      base: "0.5rem",
      md: "0.75rem",
      lg: "1rem",
      xl: "1.5rem",
      xl2: "2rem",
      xl3: "3rem",
      full: "9999px",
    },
    boxShadow: {
      none: "none",
      sm: "0 1px 2px 0 rgb(0 0 0 / 0.05)",
      base: "0 1px 3px 0 rgb(0 0 0 / 0.1), 0 1px 2px -1px rgb(0 0 0 / 0.1)",
      md: "0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)",
      lg: "0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)",
      xl: "0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.1)",
      xl2: "0 25px 50px -12px rgb(0 0 0 / 0.25)",
      inner: "inset 0 2px 4px 0 rgb(0 0 0 / 0.05)",
    },
    transition: {
      none: "none",
      all: "all 150ms cubic-bezier(0.4, 0, 0.2, 1)",
      colors:
        "background-color, border-color, color, fill, stroke 150ms cubic-bezier(0.4, 0, 0.2, 1)",
      opacity: "opacity 150ms cubic-bezier(0.4, 0, 0.2, 1)",
      shadow: "box-shadow 150ms cubic-bezier(0.4, 0, 0.2, 1)",
      transform: "transform 150ms cubic-bezier(0.4, 0, 0.2, 1)",
    },
    animation: {
      none: "none",
      spin: "spin 1s linear infinite",
      ping: "ping 1s cubic-bezier(0, 0, 0.2, 1) infinite",
      pulse: "pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite",
      bounce: "bounce 1s infinite",
      fadeIn: "fadeIn 0.5s ease-out",
      fadeOut: "fadeOut 0.5s ease-in",
      slideUp: "slideUp 0.3s ease-out",
      slideDown: "slideDown 0.3s ease-out",
    },
  },
  components: {
    button: {
      variants: {
        primary: {
          base: "bg-primary text-primary-foreground shadow-md",
          hover: "bg-primary/90 shadow-lg",
          active: "bg-primary/80",
          disabled: "opacity-50 cursor-not-allowed",
        },
        secondary: {
          base: "bg-secondary text-secondary-foreground",
          hover: "bg-secondary/90",
          active: "bg-secondary/80",
          disabled: "opacity-50 cursor-not-allowed",
        },
        outline: {
          base: "border-2 border-primary bg-transparent text-primary",
          hover: "bg-primary text-primary-foreground",
          active: "bg-primary/90",
          disabled: "opacity-50 cursor-not-allowed",
        },
        ghost: {
          base: "hover:bg-muted",
          hover: "bg-muted",
          active: "bg-muted/80",
          disabled: "opacity-50 cursor-not-allowed",
        },
      },
      sizes: {
        sm: {
          padding: "0.5rem 1rem",
          fontSize: "0.875rem",
          height: "2.5rem",
        },
        md: {
          padding: "0.75rem 1.5rem",
          fontSize: "1rem",
          height: "3rem",
        },
        lg: {
          padding: "1rem 2rem",
          fontSize: "1.125rem",
          height: "3.5rem",
        },
      },
      borderRadius: "0.75rem",
      fontWeight: "600",
      transition: "all 200ms cubic-bezier(0.4, 0, 0.2, 1)",
    },
    link: {
      base: "text-accent font-medium",
      hover: "text-accent/80 underline",
      visited: "text-accent/70",
      underline: false,
      transition: "all 200ms cubic-bezier(0.4, 0, 0.2, 1)",
    },
    card: {
      borderRadius: "1rem",
      boxShadow:
        "0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)",
      padding: "1.5rem",
      borderWidth: "0",
      borderColor: "transparent",
    },
    input: {
      borderRadius: "0.5rem",
      borderWidth: "2px",
      borderColor: "border",
      focusBorderColor: "ring",
      padding: "0.625rem 0.875rem",
      fontSize: "1rem",
      transition: "all 200ms cubic-bezier(0.4, 0, 0.2, 1)",
    },
  },
  sections: {
    hero: {
      minHeight: "70vh",
      padding: "4rem 2rem",
      textAlign: "center",
      overlayOpacity: 0.4,
    },
    about: {
      padding: "5rem 2rem",
      maxWidth: "64rem",
      textAlign: "center",
    },
    gallery: {
      padding: "5rem 2rem",
      gridCols: 3,
      gap: "1.5rem",
      aspectRatio: "square",
    },
    contact: {
      padding: "5rem 2rem",
      layout: "split",
      formWidth: "28rem",
    },
    reviews: {
      padding: "5rem 2rem",
      layout: "grid",
      itemsPerRow: 2,
    },
  },
};

// Medical/Healthcare Theme - Clean and Professional
export const medicalTheme: ThemeSchema = {
  id: "medical-modern",
  name: "Modern Medical",
  description: "Clean, professional design for healthcare providers",
  version: "2.0.0",
  darkMode: false,
  colors: {
    light: {
      primary: "#0891b2", // Cyan
      primaryForeground: "#ffffff",
      secondary: "#0e7490",
      secondaryForeground: "#ffffff",
      accent: "#06b6d4",
      accentForeground: "#ffffff",
      background: "#f0fdfa", // Very light cyan
      foreground: "#083344",
      card: "#ffffff",
      cardForeground: "#083344",
      popover: "#ffffff",
      popoverForeground: "#083344",
      muted: "#e0f2fe", // Light blue
      mutedForeground: "#0c4a6e",
      border: "#bae6fd",
      input: "#e0f2fe",
      ring: "#0891b2",
      destructive: "#dc2626",
      destructiveForeground: "#ffffff",
      success: "#059669",
      successForeground: "#ffffff",
      warning: "#f59e0b",
      warningForeground: "#ffffff",
      info: "#0284c7",
      infoForeground: "#ffffff",
    },
  },
  typography: {
    fontFamilyBase: "Inter, system-ui, -apple-system, sans-serif",
    fontFamilyHeading: "Inter, system-ui, -apple-system, sans-serif",
    fontFamilyMonospace: "Menlo, Monaco, Consolas, monospace",
    fontSize: {
      xs: "0.75rem",
      sm: "0.875rem",
      base: "1rem",
      lg: "1.125rem",
      xl: "1.25rem",
      xl2: "1.5rem",
      xl3: "1.875rem",
      xl4: "2.25rem",
      xl5: "3rem",
      xl6: "3.75rem",
      xl7: "4.5rem",
      xl8: "6rem",
      xl9: "8rem",
    },
    fontWeight: {
      thin: 100,
      extralight: 200,
      light: 300,
      normal: 400,
      medium: 500,
      semibold: 600,
      bold: 700,
      extrabold: 800,
      black: 900,
    },
    lineHeight: {
      none: "1",
      tight: "1.25",
      snug: "1.375",
      normal: "1.5",
      relaxed: "1.625",
      loose: "2",
    },
    letterSpacing: {
      tighter: "-0.05em",
      tight: "-0.025em",
      normal: "0em",
      wide: "0.025em",
      wider: "0.05em",
      widest: "0.1em",
    },
  },
  spacing: {
    spacing: {
      s0: "0px",
      s0_5: "0.125rem",
      s1: "0.25rem",
      s1_5: "0.375rem",
      s2: "0.5rem",
      s2_5: "0.625rem",
      s3: "0.75rem",
      s3_5: "0.875rem",
      s4: "1rem",
      s5: "1.25rem",
      s6: "1.5rem",
      s7: "1.75rem",
      s8: "2rem",
      s9: "2.25rem",
      s10: "2.5rem",
      s11: "2.75rem",
      s12: "3rem",
      s14: "3.5rem",
      s16: "4rem",
      s20: "5rem",
      s24: "6rem",
      s28: "7rem",
      s32: "8rem",
      s36: "9rem",
      s40: "10rem",
      s44: "11rem",
      s48: "12rem",
      s52: "13rem",
      s56: "14rem",
      s60: "15rem",
      s64: "16rem",
      s72: "18rem",
      s80: "20rem",
      s96: "24rem",
    },
    container: {
      sm: "640px",
      md: "768px",
      lg: "1024px",
      xl: "1280px",
      xl2: "1536px",
      full: "100%",
    },
    sectionSpacing: {
      none: "0",
      sm: "2rem",
      md: "4rem",
      lg: "6rem",
      xl: "8rem",
      xl2: "10rem",
    },
  },
  effects: {
    borderRadius: {
      none: "0",
      sm: "0.125rem",
      base: "0.375rem",
      md: "0.5rem",
      lg: "0.75rem",
      xl: "1rem",
      xl2: "1.5rem",
      xl3: "2rem",
      full: "9999px",
    },
    boxShadow: {
      none: "none",
      sm: "0 1px 2px 0 rgb(0 0 0 / 0.05)",
      base: "0 1px 3px 0 rgb(0 0 0 / 0.1), 0 1px 2px -1px rgb(0 0 0 / 0.1)",
      md: "0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)",
      lg: "0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)",
      xl: "0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.1)",
      xl2: "0 25px 50px -12px rgb(0 0 0 / 0.25)",
      inner: "inset 0 2px 4px 0 rgb(0 0 0 / 0.05)",
    },
    transition: {
      none: "none",
      all: "all 150ms cubic-bezier(0.4, 0, 0.2, 1)",
      colors:
        "background-color, border-color, color, fill, stroke 150ms cubic-bezier(0.4, 0, 0.2, 1)",
      opacity: "opacity 150ms cubic-bezier(0.4, 0, 0.2, 1)",
      shadow: "box-shadow 150ms cubic-bezier(0.4, 0, 0.2, 1)",
      transform: "transform 150ms cubic-bezier(0.4, 0, 0.2, 1)",
    },
    animation: {
      none: "none",
      spin: "spin 1s linear infinite",
      ping: "ping 1s cubic-bezier(0, 0, 0.2, 1) infinite",
      pulse: "pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite",
      bounce: "bounce 1s infinite",
      fadeIn: "fadeIn 0.5s ease-out",
      fadeOut: "fadeOut 0.5s ease-in",
      slideUp: "slideUp 0.3s ease-out",
      slideDown: "slideDown 0.3s ease-out",
    },
  },
  components: {
    button: {
      variants: {
        primary: {
          base: "bg-primary text-primary-foreground",
          hover: "bg-primary/90",
          active: "bg-primary/80",
          disabled: "opacity-50 cursor-not-allowed",
        },
        secondary: {
          base: "bg-secondary text-secondary-foreground",
          hover: "bg-secondary/90",
          active: "bg-secondary/80",
          disabled: "opacity-50 cursor-not-allowed",
        },
        outline: {
          base: "border border-primary bg-transparent text-primary",
          hover: "bg-primary/10",
          active: "bg-primary/20",
          disabled: "opacity-50 cursor-not-allowed",
        },
        ghost: {
          base: "hover:bg-muted",
          hover: "bg-muted",
          active: "bg-muted/80",
          disabled: "opacity-50 cursor-not-allowed",
        },
      },
      sizes: {
        sm: {
          padding: "0.375rem 0.875rem",
          fontSize: "0.875rem",
          height: "2.25rem",
        },
        md: {
          padding: "0.5rem 1rem",
          fontSize: "1rem",
          height: "2.75rem",
        },
        lg: {
          padding: "0.625rem 1.25rem",
          fontSize: "1.125rem",
          height: "3.25rem",
        },
      },
      borderRadius: "0.5rem",
      fontWeight: "500",
      transition: "all 150ms cubic-bezier(0.4, 0, 0.2, 1)",
    },
    link: {
      base: "text-primary",
      hover: "text-primary/80 underline",
      visited: "text-primary/70",
      underline: false,
      transition: "all 150ms cubic-bezier(0.4, 0, 0.2, 1)",
    },
    card: {
      borderRadius: "0.5rem",
      boxShadow:
        "0 1px 3px 0 rgb(0 0 0 / 0.1), 0 1px 2px -1px rgb(0 0 0 / 0.1)",
      padding: "1.5rem",
      borderWidth: "1px",
      borderColor: "border",
    },
    input: {
      borderRadius: "0.375rem",
      borderWidth: "1px",
      borderColor: "border",
      focusBorderColor: "ring",
      padding: "0.5rem 0.75rem",
      fontSize: "1rem",
      transition: "all 150ms cubic-bezier(0.4, 0, 0.2, 1)",
    },
  },
  sections: {
    hero: {
      minHeight: "50vh",
      padding: "3rem 2rem",
      textAlign: "left",
      overlayOpacity: 0.2,
    },
    about: {
      padding: "3rem 2rem",
      maxWidth: "64rem",
      textAlign: "left",
    },
    gallery: {
      padding: "3rem 2rem",
      gridCols: 3,
      gap: "1.5rem",
      aspectRatio: "video",
    },
    contact: {
      padding: "3rem 2rem",
      layout: "split",
      formWidth: "32rem",
    },
    reviews: {
      padding: "3rem 2rem",
      layout: "list",
      itemsPerRow: 1,
    },
  },
};

// Beauty/Salon Theme - Elegant and Soft
export const beautyTheme: ThemeSchema = {
  id: "beauty-modern",
  name: "Modern Beauty",
  description: "Elegant and sophisticated design for beauty businesses",
  version: "2.0.0",
  darkMode: true,
  colors: {
    light: {
      primary: "#db2777", // Pink
      primaryForeground: "#ffffff",
      secondary: "#fbbf24", // Gold
      secondaryForeground: "#78350f",
      accent: "#f472b6", // Light pink
      accentForeground: "#500724",
      background: "#fdf2f8", // Very light pink
      foreground: "#500724",
      card: "#ffffff",
      cardForeground: "#500724",
      popover: "#ffffff",
      popoverForeground: "#500724",
      muted: "#fce7f3", // Light pink
      mutedForeground: "#9f1239",
      border: "#fbcfe8",
      input: "#fce7f3",
      ring: "#ec4899",
      destructive: "#dc2626",
      destructiveForeground: "#ffffff",
      success: "#059669",
      successForeground: "#ffffff",
      warning: "#f59e0b",
      warningForeground: "#ffffff",
      info: "#3b82f6",
      infoForeground: "#ffffff",
    },
    dark: {
      primary: "#f472b6", // Light pink
      primaryForeground: "#500724",
      secondary: "#fbbf24", // Gold
      secondaryForeground: "#78350f",
      accent: "#f9a8d4", // Very light pink
      accentForeground: "#500724",
      background: "#190211", // Deep purple-black
      foreground: "#fdf2f8",
      card: "#500724",
      cardForeground: "#fdf2f8",
      popover: "#500724",
      popoverForeground: "#fdf2f8",
      muted: "#831843",
      mutedForeground: "#fbcfe8",
      border: "#9f1239",
      input: "#831843",
      ring: "#f472b6",
      destructive: "#ef4444",
      destructiveForeground: "#ffffff",
      success: "#10b981",
      successForeground: "#ffffff",
      warning: "#f59e0b",
      warningForeground: "#ffffff",
      info: "#60a5fa",
      infoForeground: "#ffffff",
    },
  },
  typography: {
    fontFamilyBase: "Montserrat, system-ui, -apple-system, sans-serif",
    fontFamilyHeading: "Cormorant Garamond, Georgia, serif",
    fontFamilyMonospace: "Menlo, Monaco, Consolas, monospace",
    fontSize: {
      xs: "0.75rem",
      sm: "0.875rem",
      base: "1rem",
      lg: "1.125rem",
      xl: "1.25rem",
      xl2: "1.5rem",
      xl3: "1.875rem",
      xl4: "2.25rem",
      xl5: "3rem",
      xl6: "3.75rem",
      xl7: "4.5rem",
      xl8: "6rem",
      xl9: "8rem",
    },
    fontWeight: {
      thin: 100,
      extralight: 200,
      light: 300,
      normal: 400,
      medium: 500,
      semibold: 600,
      bold: 700,
      extrabold: 800,
      black: 900,
    },
    lineHeight: {
      none: "1",
      tight: "1.25",
      snug: "1.375",
      normal: "1.5",
      relaxed: "1.625",
      loose: "2",
    },
    letterSpacing: {
      tighter: "-0.05em",
      tight: "-0.025em",
      normal: "0.025em",
      wide: "0.05em",
      wider: "0.1em",
      widest: "0.15em",
    },
  },
  spacing: {
    spacing: {
      s0: "0px",
      s0_5: "0.125rem",
      s1: "0.25rem",
      s1_5: "0.375rem",
      s2: "0.5rem",
      s2_5: "0.625rem",
      s3: "0.75rem",
      s3_5: "0.875rem",
      s4: "1rem",
      s5: "1.25rem",
      s6: "1.5rem",
      s7: "1.75rem",
      s8: "2rem",
      s9: "2.25rem",
      s10: "2.5rem",
      s11: "2.75rem",
      s12: "3rem",
      s14: "3.5rem",
      s16: "4rem",
      s20: "5rem",
      s24: "6rem",
      s28: "7rem",
      s32: "8rem",
      s36: "9rem",
      s40: "10rem",
      s44: "11rem",
      s48: "12rem",
      s52: "13rem",
      s56: "14rem",
      s60: "15rem",
      s64: "16rem",
      s72: "18rem",
      s80: "20rem",
      s96: "24rem",
    },
    container: {
      sm: "640px",
      md: "768px",
      lg: "1024px",
      xl: "1280px",
      xl2: "1536px",
      full: "100%",
    },
    sectionSpacing: {
      none: "0",
      sm: "2rem",
      md: "4rem",
      lg: "6rem",
      xl: "8rem",
      xl2: "10rem",
    },
  },
  effects: {
    borderRadius: {
      none: "0",
      sm: "0.5rem",
      base: "1rem",
      md: "1.5rem",
      lg: "2rem",
      xl: "3rem",
      xl2: "4rem",
      xl3: "5rem",
      full: "9999px",
    },
    boxShadow: {
      none: "none",
      sm: "0 1px 2px 0 rgb(0 0 0 / 0.05)",
      base: "0 1px 3px 0 rgb(0 0 0 / 0.1), 0 1px 2px -1px rgb(0 0 0 / 0.1)",
      md: "0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)",
      lg: "0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)",
      xl: "0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.1)",
      xl2: "0 25px 50px -12px rgb(0 0 0 / 0.25)",
      inner: "inset 0 2px 4px 0 rgb(0 0 0 / 0.05)",
    },
    transition: {
      none: "none",
      all: "all 300ms cubic-bezier(0.4, 0, 0.2, 1)",
      colors:
        "background-color, border-color, color, fill, stroke 300ms cubic-bezier(0.4, 0, 0.2, 1)",
      opacity: "opacity 300ms cubic-bezier(0.4, 0, 0.2, 1)",
      shadow: "box-shadow 300ms cubic-bezier(0.4, 0, 0.2, 1)",
      transform: "transform 300ms cubic-bezier(0.4, 0, 0.2, 1)",
    },
    animation: {
      none: "none",
      spin: "spin 1s linear infinite",
      ping: "ping 1s cubic-bezier(0, 0, 0.2, 1) infinite",
      pulse: "pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite",
      bounce: "bounce 1s infinite",
      fadeIn: "fadeIn 0.5s ease-out",
      fadeOut: "fadeOut 0.5s ease-in",
      slideUp: "slideUp 0.3s ease-out",
      slideDown: "slideDown 0.3s ease-out",
    },
  },
  components: {
    button: {
      variants: {
        primary: {
          base: "bg-primary text-primary-foreground shadow-md",
          hover: "bg-primary/90 shadow-lg",
          active: "bg-primary/80",
          disabled: "opacity-50 cursor-not-allowed",
        },
        secondary: {
          base: "bg-secondary text-secondary-foreground",
          hover: "bg-secondary/90",
          active: "bg-secondary/80",
          disabled: "opacity-50 cursor-not-allowed",
        },
        outline: {
          base: "border-2 border-primary bg-transparent text-primary",
          hover: "bg-primary/10",
          active: "bg-primary/20",
          disabled: "opacity-50 cursor-not-allowed",
        },
        ghost: {
          base: "hover:bg-muted",
          hover: "bg-muted",
          active: "bg-muted/80",
          disabled: "opacity-50 cursor-not-allowed",
        },
      },
      sizes: {
        sm: {
          padding: "0.5rem 1.25rem",
          fontSize: "0.875rem",
          height: "2.5rem",
        },
        md: {
          padding: "0.75rem 1.75rem",
          fontSize: "1rem",
          height: "3rem",
        },
        lg: {
          padding: "1rem 2.25rem",
          fontSize: "1.125rem",
          height: "3.5rem",
        },
      },
      borderRadius: "2rem",
      fontWeight: "500",
      transition: "all 300ms cubic-bezier(0.4, 0, 0.2, 1)",
    },
    link: {
      base: "text-accent",
      hover: "text-accent/80 underline",
      visited: "text-accent/70",
      underline: false,
      transition: "all 300ms cubic-bezier(0.4, 0, 0.2, 1)",
    },
    card: {
      borderRadius: "1.5rem",
      boxShadow:
        "0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)",
      padding: "2rem",
      borderWidth: "0",
      borderColor: "transparent",
    },
    input: {
      borderRadius: "1rem",
      borderWidth: "1px",
      borderColor: "border",
      focusBorderColor: "ring",
      padding: "0.75rem 1rem",
      fontSize: "1rem",
      transition: "all 300ms cubic-bezier(0.4, 0, 0.2, 1)",
    },
  },
  sections: {
    hero: {
      minHeight: "60vh",
      padding: "5rem 2rem",
      textAlign: "center",
      overlayOpacity: 0.3,
    },
    about: {
      padding: "5rem 2rem",
      maxWidth: "48rem",
      textAlign: "center",
    },
    gallery: {
      padding: "5rem 2rem",
      gridCols: 4,
      gap: "1rem",
      aspectRatio: "portrait",
    },
    contact: {
      padding: "5rem 2rem",
      layout: "centered",
      formWidth: "32rem",
    },
    reviews: {
      padding: "5rem 2rem",
      layout: "carousel",
      itemsPerRow: 1,
    },
  },
};

// Fitness/Gym Theme - Bold and Energetic
export const fitnessTheme: ThemeSchema = {
  id: "fitness-modern",
  name: "Modern Fitness",
  description: "Bold and energetic design for fitness businesses",
  version: "2.0.0",
  darkMode: true,
  colors: {
    light: {
      primary: "#ef4444", // Red
      primaryForeground: "#ffffff",
      secondary: "#171717", // Near black
      secondaryForeground: "#ffffff",
      accent: "#f59e0b", // Amber
      accentForeground: "#451a03",
      background: "#fafafa",
      foreground: "#171717",
      card: "#ffffff",
      cardForeground: "#171717",
      popover: "#ffffff",
      popoverForeground: "#171717",
      muted: "#f5f5f5",
      mutedForeground: "#525252",
      border: "#e5e5e5",
      input: "#f5f5f5",
      ring: "#ef4444",
      destructive: "#b91c1c",
      destructiveForeground: "#ffffff",
      success: "#16a34a",
      successForeground: "#ffffff",
      warning: "#f59e0b",
      warningForeground: "#ffffff",
      info: "#0284c7",
      infoForeground: "#ffffff",
    },
    dark: {
      primary: "#ef4444", // Red
      primaryForeground: "#ffffff",
      secondary: "#fafafa", // Near white
      secondaryForeground: "#171717",
      accent: "#fbbf24", // Bright amber
      accentForeground: "#451a03",
      background: "#0a0a0a",
      foreground: "#fafafa",
      card: "#171717",
      cardForeground: "#fafafa",
      popover: "#171717",
      popoverForeground: "#fafafa",
      muted: "#262626",
      mutedForeground: "#a3a3a3",
      border: "#404040",
      input: "#262626",
      ring: "#ef4444",
      destructive: "#dc2626",
      destructiveForeground: "#ffffff",
      success: "#22c55e",
      successForeground: "#ffffff",
      warning: "#f59e0b",
      warningForeground: "#ffffff",
      info: "#06b6d4",
      infoForeground: "#ffffff",
    },
  },
  typography: {
    fontFamilyBase: "Oswald, system-ui, -apple-system, sans-serif",
    fontFamilyHeading: "Bebas Neue, system-ui, -apple-system, sans-serif",
    fontFamilyMonospace: "Menlo, Monaco, Consolas, monospace",
    fontSize: {
      xs: "0.75rem",
      sm: "0.875rem",
      base: "1rem",
      lg: "1.125rem",
      xl: "1.25rem",
      xl2: "1.5rem",
      xl3: "1.875rem",
      xl4: "2.25rem",
      xl5: "3rem",
      xl6: "3.75rem",
      xl7: "4.5rem",
      xl8: "6rem",
      xl9: "8rem",
    },
    fontWeight: {
      thin: 100,
      extralight: 200,
      light: 300,
      normal: 400,
      medium: 500,
      semibold: 600,
      bold: 700,
      extrabold: 800,
      black: 900,
    },
    lineHeight: {
      none: "1",
      tight: "1.1",
      snug: "1.25",
      normal: "1.4",
      relaxed: "1.5",
      loose: "1.75",
    },
    letterSpacing: {
      tighter: "-0.05em",
      tight: "-0.025em",
      normal: "0em",
      wide: "0.025em",
      wider: "0.05em",
      widest: "0.1em",
    },
  },
  spacing: {
    spacing: {
      s0: "0px",
      s0_5: "0.125rem",
      s1: "0.25rem",
      s1_5: "0.375rem",
      s2: "0.5rem",
      s2_5: "0.625rem",
      s3: "0.75rem",
      s3_5: "0.875rem",
      s4: "1rem",
      s5: "1.25rem",
      s6: "1.5rem",
      s7: "1.75rem",
      s8: "2rem",
      s9: "2.25rem",
      s10: "2.5rem",
      s11: "2.75rem",
      s12: "3rem",
      s14: "3.5rem",
      s16: "4rem",
      s20: "5rem",
      s24: "6rem",
      s28: "7rem",
      s32: "8rem",
      s36: "9rem",
      s40: "10rem",
      s44: "11rem",
      s48: "12rem",
      s52: "13rem",
      s56: "14rem",
      s60: "15rem",
      s64: "16rem",
      s72: "18rem",
      s80: "20rem",
      s96: "24rem",
    },
    container: {
      sm: "640px",
      md: "768px",
      lg: "1024px",
      xl: "1280px",
      xl2: "1536px",
      full: "100%",
    },
    sectionSpacing: {
      none: "0",
      sm: "2rem",
      md: "4rem",
      lg: "6rem",
      xl: "8rem",
      xl2: "10rem",
    },
  },
  effects: {
    borderRadius: {
      none: "0",
      sm: "0.125rem",
      base: "0.25rem",
      md: "0.375rem",
      lg: "0.5rem",
      xl: "0.75rem",
      xl2: "1rem",
      xl3: "1.5rem",
      full: "9999px",
    },
    boxShadow: {
      none: "none",
      sm: "0 1px 2px 0 rgb(0 0 0 / 0.05)",
      base: "0 1px 3px 0 rgb(0 0 0 / 0.1), 0 1px 2px -1px rgb(0 0 0 / 0.1)",
      md: "0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)",
      lg: "0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)",
      xl: "0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.1)",
      xl2: "0 25px 50px -12px rgb(0 0 0 / 0.25)",
      inner: "inset 0 2px 4px 0 rgb(0 0 0 / 0.05)",
    },
    transition: {
      none: "none",
      all: "all 150ms cubic-bezier(0.4, 0, 0.2, 1)",
      colors:
        "background-color, border-color, color, fill, stroke 150ms cubic-bezier(0.4, 0, 0.2, 1)",
      opacity: "opacity 150ms cubic-bezier(0.4, 0, 0.2, 1)",
      shadow: "box-shadow 150ms cubic-bezier(0.4, 0, 0.2, 1)",
      transform: "transform 150ms cubic-bezier(0.4, 0, 0.2, 1)",
    },
    animation: {
      none: "none",
      spin: "spin 1s linear infinite",
      ping: "ping 1s cubic-bezier(0, 0, 0.2, 1) infinite",
      pulse: "pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite",
      bounce: "bounce 1s infinite",
      fadeIn: "fadeIn 0.5s ease-out",
      fadeOut: "fadeOut 0.5s ease-in",
      slideUp: "slideUp 0.3s ease-out",
      slideDown: "slideDown 0.3s ease-out",
    },
  },
  components: {
    button: {
      variants: {
        primary: {
          base: "bg-primary text-primary-foreground uppercase tracking-wider shadow-lg",
          hover: "bg-primary/90 scale-105",
          active: "bg-primary/80 scale-100",
          disabled: "opacity-50 cursor-not-allowed",
        },
        secondary: {
          base: "bg-secondary text-secondary-foreground uppercase tracking-wider",
          hover: "bg-secondary/90",
          active: "bg-secondary/80",
          disabled: "opacity-50 cursor-not-allowed",
        },
        outline: {
          base: "border-2 border-primary bg-transparent text-primary uppercase tracking-wider",
          hover: "bg-primary text-primary-foreground",
          active: "bg-primary/90",
          disabled: "opacity-50 cursor-not-allowed",
        },
        ghost: {
          base: "hover:bg-muted uppercase tracking-wider",
          hover: "bg-muted",
          active: "bg-muted/80",
          disabled: "opacity-50 cursor-not-allowed",
        },
      },
      sizes: {
        sm: {
          padding: "0.5rem 1rem",
          fontSize: "0.875rem",
          height: "2.5rem",
        },
        md: {
          padding: "0.75rem 1.5rem",
          fontSize: "1rem",
          height: "3rem",
        },
        lg: {
          padding: "1rem 2rem",
          fontSize: "1.25rem",
          height: "3.75rem",
        },
      },
      borderRadius: "0.125rem",
      fontWeight: "700",
      transition: "all 150ms cubic-bezier(0.4, 0, 0.2, 1)",
    },
    link: {
      base: "text-primary font-bold uppercase tracking-wide",
      hover: "text-primary/80 underline",
      visited: "text-primary/70",
      underline: false,
      transition: "all 150ms cubic-bezier(0.4, 0, 0.2, 1)",
    },
    card: {
      borderRadius: "0.25rem",
      boxShadow:
        "0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)",
      padding: "1.5rem",
      borderWidth: "0",
      borderColor: "transparent",
    },
    input: {
      borderRadius: "0.125rem",
      borderWidth: "2px",
      borderColor: "border",
      focusBorderColor: "ring",
      padding: "0.75rem 1rem",
      fontSize: "1rem",
      transition: "all 150ms cubic-bezier(0.4, 0, 0.2, 1)",
    },
  },
  sections: {
    hero: {
      minHeight: "80vh",
      padding: "4rem 2rem",
      textAlign: "center",
      overlayOpacity: 0.7,
    },
    about: {
      padding: "4rem 2rem",
      maxWidth: "64rem",
      textAlign: "center",
    },
    gallery: {
      padding: "4rem 2rem",
      gridCols: 3,
      gap: "1rem",
      aspectRatio: "video",
    },
    contact: {
      padding: "4rem 2rem",
      layout: "split",
      formWidth: "28rem",
    },
    reviews: {
      padding: "4rem 2rem",
      layout: "grid",
      itemsPerRow: 3,
    },
  },
};

// Professional Services Theme - Clean and Trustworthy
export const professionalTheme: ThemeSchema = {
  id: "professional-modern",
  name: "Modern Professional",
  description: "Clean and professional design for service businesses",
  version: "2.0.0",
  darkMode: true,
  colors: {
    light: {
      primary: "#1e40af", // Blue
      primaryForeground: "#ffffff",
      secondary: "#64748b", // Slate
      secondaryForeground: "#ffffff",
      accent: "#0891b2", // Cyan
      accentForeground: "#ffffff",
      background: "#f8fafc",
      foreground: "#0f172a",
      card: "#ffffff",
      cardForeground: "#0f172a",
      popover: "#ffffff",
      popoverForeground: "#0f172a",
      muted: "#f1f5f9",
      mutedForeground: "#64748b",
      border: "#e2e8f0",
      input: "#e2e8f0",
      ring: "#1e40af",
      destructive: "#dc2626",
      destructiveForeground: "#ffffff",
      success: "#059669",
      successForeground: "#ffffff",
      warning: "#d97706",
      warningForeground: "#ffffff",
      info: "#0284c7",
      infoForeground: "#ffffff",
    },
    dark: {
      primary: "#3b82f6", // Bright blue
      primaryForeground: "#ffffff",
      secondary: "#94a3b8", // Light slate
      secondaryForeground: "#0f172a",
      accent: "#06b6d4", // Bright cyan
      accentForeground: "#ffffff",
      background: "#0f172a",
      foreground: "#f8fafc",
      card: "#1e293b",
      cardForeground: "#f8fafc",
      popover: "#1e293b",
      popoverForeground: "#f8fafc",
      muted: "#334155",
      mutedForeground: "#cbd5e1",
      border: "#475569",
      input: "#334155",
      ring: "#3b82f6",
      destructive: "#ef4444",
      destructiveForeground: "#ffffff",
      success: "#10b981",
      successForeground: "#ffffff",
      warning: "#f59e0b",
      warningForeground: "#ffffff",
      info: "#06b6d4",
      infoForeground: "#ffffff",
    },
  },
  typography: {
    fontFamilyBase: "Inter, system-ui, -apple-system, sans-serif",
    fontFamilyHeading: "Inter, system-ui, -apple-system, sans-serif",
    fontFamilyMonospace: "Menlo, Monaco, Consolas, monospace",
    fontSize: {
      xs: "0.75rem",
      sm: "0.875rem",
      base: "1rem",
      lg: "1.125rem",
      xl: "1.25rem",
      xl2: "1.5rem",
      xl3: "1.875rem",
      xl4: "2.25rem",
      xl5: "3rem",
      xl6: "3.75rem",
      xl7: "4.5rem",
      xl8: "6rem",
      xl9: "8rem",
    },
    fontWeight: {
      thin: 100,
      extralight: 200,
      light: 300,
      normal: 400,
      medium: 500,
      semibold: 600,
      bold: 700,
      extrabold: 800,
      black: 900,
    },
    lineHeight: {
      none: "1",
      tight: "1.25",
      snug: "1.375",
      normal: "1.5",
      relaxed: "1.625",
      loose: "2",
    },
    letterSpacing: {
      tighter: "-0.05em",
      tight: "-0.025em",
      normal: "0em",
      wide: "0.025em",
      wider: "0.05em",
      widest: "0.1em",
    },
  },
  spacing: {
    spacing: {
      s0: "0px",
      s0_5: "0.125rem",
      s1: "0.25rem",
      s1_5: "0.375rem",
      s2: "0.5rem",
      s2_5: "0.625rem",
      s3: "0.75rem",
      s3_5: "0.875rem",
      s4: "1rem",
      s5: "1.25rem",
      s6: "1.5rem",
      s7: "1.75rem",
      s8: "2rem",
      s9: "2.25rem",
      s10: "2.5rem",
      s11: "2.75rem",
      s12: "3rem",
      s14: "3.5rem",
      s16: "4rem",
      s20: "5rem",
      s24: "6rem",
      s28: "7rem",
      s32: "8rem",
      s36: "9rem",
      s40: "10rem",
      s44: "11rem",
      s48: "12rem",
      s52: "13rem",
      s56: "14rem",
      s60: "15rem",
      s64: "16rem",
      s72: "18rem",
      s80: "20rem",
      s96: "24rem",
    },
    container: {
      sm: "640px",
      md: "768px",
      lg: "1024px",
      xl: "1280px",
      xl2: "1536px",
      full: "100%",
    },
    sectionSpacing: {
      none: "0",
      sm: "2rem",
      md: "4rem",
      lg: "6rem",
      xl: "8rem",
      xl2: "10rem",
    },
  },
  effects: {
    borderRadius: {
      none: "0",
      sm: "0.125rem",
      base: "0.375rem",
      md: "0.5rem",
      lg: "0.75rem",
      xl: "1rem",
      xl2: "1.5rem",
      xl3: "2rem",
      full: "9999px",
    },
    boxShadow: {
      none: "none",
      sm: "0 1px 2px 0 rgb(0 0 0 / 0.05)",
      base: "0 1px 3px 0 rgb(0 0 0 / 0.1), 0 1px 2px -1px rgb(0 0 0 / 0.1)",
      md: "0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)",
      lg: "0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)",
      xl: "0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.1)",
      xl2: "0 25px 50px -12px rgb(0 0 0 / 0.25)",
      inner: "inset 0 2px 4px 0 rgb(0 0 0 / 0.05)",
    },
    transition: {
      none: "none",
      all: "all 150ms cubic-bezier(0.4, 0, 0.2, 1)",
      colors:
        "background-color, border-color, color, fill, stroke 150ms cubic-bezier(0.4, 0, 0.2, 1)",
      opacity: "opacity 150ms cubic-bezier(0.4, 0, 0.2, 1)",
      shadow: "box-shadow 150ms cubic-bezier(0.4, 0, 0.2, 1)",
      transform: "transform 150ms cubic-bezier(0.4, 0, 0.2, 1)",
    },
    animation: {
      none: "none",
      spin: "spin 1s linear infinite",
      ping: "ping 1s cubic-bezier(0, 0, 0.2, 1) infinite",
      pulse: "pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite",
      bounce: "bounce 1s infinite",
      fadeIn: "fadeIn 0.5s ease-out",
      fadeOut: "fadeOut 0.5s ease-in",
      slideUp: "slideUp 0.3s ease-out",
      slideDown: "slideDown 0.3s ease-out",
    },
  },
  components: {
    button: {
      variants: {
        primary: {
          base: "bg-primary text-primary-foreground shadow-sm",
          hover: "bg-primary/90",
          active: "bg-primary/80",
          disabled: "opacity-50 cursor-not-allowed",
        },
        secondary: {
          base: "bg-secondary text-secondary-foreground shadow-sm",
          hover: "bg-secondary/90",
          active: "bg-secondary/80",
          disabled: "opacity-50 cursor-not-allowed",
        },
        outline: {
          base: "border border-input bg-background",
          hover: "bg-muted",
          active: "bg-muted/80",
          disabled: "opacity-50 cursor-not-allowed",
        },
        ghost: {
          base: "hover:bg-muted",
          hover: "bg-muted",
          active: "bg-muted/80",
          disabled: "opacity-50 cursor-not-allowed",
        },
      },
      sizes: {
        sm: {
          padding: "0.375rem 0.75rem",
          fontSize: "0.875rem",
          height: "2rem",
        },
        md: {
          padding: "0.5rem 1rem",
          fontSize: "0.875rem",
          height: "2.5rem",
        },
        lg: {
          padding: "0.625rem 1.25rem",
          fontSize: "1rem",
          height: "3rem",
        },
      },
      borderRadius: "0.375rem",
      fontWeight: "500",
      transition: "all 150ms cubic-bezier(0.4, 0, 0.2, 1)",
    },
    link: {
      base: "text-primary underline-offset-4",
      hover: "text-primary/80 underline",
      visited: "text-primary/70",
      underline: false,
      transition: "all 150ms cubic-bezier(0.4, 0, 0.2, 1)",
    },
    card: {
      borderRadius: "0.5rem",
      boxShadow:
        "0 1px 3px 0 rgb(0 0 0 / 0.1), 0 1px 2px -1px rgb(0 0 0 / 0.1)",
      padding: "1.5rem",
      borderWidth: "1px",
      borderColor: "border",
    },
    input: {
      borderRadius: "0.375rem",
      borderWidth: "1px",
      borderColor: "border",
      focusBorderColor: "ring",
      padding: "0.5rem 0.75rem",
      fontSize: "0.875rem",
      transition: "all 150ms cubic-bezier(0.4, 0, 0.2, 1)",
    },
  },
  sections: {
    hero: {
      minHeight: "50vh",
      padding: "3rem 1.5rem",
      textAlign: "left",
      overlayOpacity: 0.4,
    },
    about: {
      padding: "3rem 1.5rem",
      maxWidth: "64rem",
      textAlign: "left",
    },
    gallery: {
      padding: "3rem 1.5rem",
      gridCols: 3,
      gap: "1.5rem",
      aspectRatio: "video",
    },
    contact: {
      padding: "3rem 1.5rem",
      layout: "split",
      formWidth: "28rem",
    },
    reviews: {
      padding: "3rem 1.5rem",
      layout: "list",
      itemsPerRow: 1,
    },
  },
};

// Retail/Shopping Theme - Modern and Trendy
export const retailTheme: ThemeSchema = {
  id: "retail-modern",
  name: "Modern Retail",
  description: "Trendy and modern design for retail businesses",
  version: "2.0.0",
  darkMode: true,
  colors: {
    light: {
      primary: "#7c3aed", // Purple
      primaryForeground: "#ffffff",
      secondary: "#10b981", // Green
      secondaryForeground: "#ffffff",
      accent: "#f59e0b", // Amber
      accentForeground: "#451a03",
      background: "#fafafa",
      foreground: "#18181b",
      card: "#ffffff",
      cardForeground: "#18181b",
      popover: "#ffffff",
      popoverForeground: "#18181b",
      muted: "#f4f4f5",
      mutedForeground: "#71717a",
      border: "#e4e4e7",
      input: "#f4f4f5",
      ring: "#7c3aed",
      destructive: "#dc2626",
      destructiveForeground: "#ffffff",
      success: "#059669",
      successForeground: "#ffffff",
      warning: "#f59e0b",
      warningForeground: "#ffffff",
      info: "#3b82f6",
      infoForeground: "#ffffff",
    },
    dark: {
      primary: "#a78bfa", // Light purple
      primaryForeground: "#1e1b4b",
      secondary: "#34d399", // Light green
      secondaryForeground: "#022c22",
      accent: "#fbbf24", // Bright amber
      accentForeground: "#451a03",
      background: "#09090b",
      foreground: "#fafafa",
      card: "#18181b",
      cardForeground: "#fafafa",
      popover: "#18181b",
      popoverForeground: "#fafafa",
      muted: "#27272a",
      mutedForeground: "#a1a1aa",
      border: "#3f3f46",
      input: "#27272a",
      ring: "#a78bfa",
      destructive: "#ef4444",
      destructiveForeground: "#ffffff",
      success: "#10b981",
      successForeground: "#ffffff",
      warning: "#f59e0b",
      warningForeground: "#ffffff",
      info: "#60a5fa",
      infoForeground: "#ffffff",
    },
  },
  typography: {
    fontFamilyBase: "Poppins, system-ui, -apple-system, sans-serif",
    fontFamilyHeading: "Poppins, system-ui, -apple-system, sans-serif",
    fontFamilyMonospace: "Menlo, Monaco, Consolas, monospace",
    fontSize: {
      xs: "0.75rem",
      sm: "0.875rem",
      base: "1rem",
      lg: "1.125rem",
      xl: "1.25rem",
      xl2: "1.5rem",
      xl3: "1.875rem",
      xl4: "2.25rem",
      xl5: "3rem",
      xl6: "3.75rem",
      xl7: "4.5rem",
      xl8: "6rem",
      xl9: "8rem",
    },
    fontWeight: {
      thin: 100,
      extralight: 200,
      light: 300,
      normal: 400,
      medium: 500,
      semibold: 600,
      bold: 700,
      extrabold: 800,
      black: 900,
    },
    lineHeight: {
      none: "1",
      tight: "1.25",
      snug: "1.375",
      normal: "1.5",
      relaxed: "1.625",
      loose: "2",
    },
    letterSpacing: {
      tighter: "-0.05em",
      tight: "-0.025em",
      normal: "0em",
      wide: "0.025em",
      wider: "0.05em",
      widest: "0.1em",
    },
  },
  spacing: {
    spacing: {
      s0: "0px",
      s0_5: "0.125rem",
      s1: "0.25rem",
      s1_5: "0.375rem",
      s2: "0.5rem",
      s2_5: "0.625rem",
      s3: "0.75rem",
      s3_5: "0.875rem",
      s4: "1rem",
      s5: "1.25rem",
      s6: "1.5rem",
      s7: "1.75rem",
      s8: "2rem",
      s9: "2.25rem",
      s10: "2.5rem",
      s11: "2.75rem",
      s12: "3rem",
      s14: "3.5rem",
      s16: "4rem",
      s20: "5rem",
      s24: "6rem",
      s28: "7rem",
      s32: "8rem",
      s36: "9rem",
      s40: "10rem",
      s44: "11rem",
      s48: "12rem",
      s52: "13rem",
      s56: "14rem",
      s60: "15rem",
      s64: "16rem",
      s72: "18rem",
      s80: "20rem",
      s96: "24rem",
    },
    container: {
      sm: "640px",
      md: "768px",
      lg: "1024px",
      xl: "1280px",
      xl2: "1536px",
      full: "100%",
    },
    sectionSpacing: {
      none: "0",
      sm: "2rem",
      md: "4rem",
      lg: "6rem",
      xl: "8rem",
      xl2: "10rem",
    },
  },
  effects: {
    borderRadius: {
      none: "0",
      sm: "0.25rem",
      base: "0.5rem",
      md: "0.75rem",
      lg: "1rem",
      xl: "1.5rem",
      xl2: "2rem",
      xl3: "3rem",
      full: "9999px",
    },
    boxShadow: {
      none: "none",
      sm: "0 1px 2px 0 rgb(0 0 0 / 0.05)",
      base: "0 1px 3px 0 rgb(0 0 0 / 0.1), 0 1px 2px -1px rgb(0 0 0 / 0.1)",
      md: "0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)",
      lg: "0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)",
      xl: "0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.1)",
      xl2: "0 25px 50px -12px rgb(0 0 0 / 0.25)",
      inner: "inset 0 2px 4px 0 rgb(0 0 0 / 0.05)",
    },
    transition: {
      none: "none",
      all: "all 200ms cubic-bezier(0.4, 0, 0.2, 1)",
      colors:
        "background-color, border-color, color, fill, stroke 200ms cubic-bezier(0.4, 0, 0.2, 1)",
      opacity: "opacity 200ms cubic-bezier(0.4, 0, 0.2, 1)",
      shadow: "box-shadow 200ms cubic-bezier(0.4, 0, 0.2, 1)",
      transform: "transform 200ms cubic-bezier(0.4, 0, 0.2, 1)",
    },
    animation: {
      none: "none",
      spin: "spin 1s linear infinite",
      ping: "ping 1s cubic-bezier(0, 0, 0.2, 1) infinite",
      pulse: "pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite",
      bounce: "bounce 1s infinite",
      fadeIn: "fadeIn 0.5s ease-out",
      fadeOut: "fadeOut 0.5s ease-in",
      slideUp: "slideUp 0.3s ease-out",
      slideDown: "slideDown 0.3s ease-out",
    },
  },
  components: {
    button: {
      variants: {
        primary: {
          base: "bg-primary text-primary-foreground shadow-lg",
          hover: "bg-primary/90 scale-105",
          active: "bg-primary/80 scale-100",
          disabled: "opacity-50 cursor-not-allowed",
        },
        secondary: {
          base: "bg-secondary text-secondary-foreground shadow-lg",
          hover: "bg-secondary/90 scale-105",
          active: "bg-secondary/80 scale-100",
          disabled: "opacity-50 cursor-not-allowed",
        },
        outline: {
          base: "border-2 border-primary bg-background",
          hover: "bg-primary text-primary-foreground",
          active: "bg-primary/90",
          disabled: "opacity-50 cursor-not-allowed",
        },
        ghost: {
          base: "hover:bg-muted",
          hover: "bg-muted",
          active: "bg-muted/80",
          disabled: "opacity-50 cursor-not-allowed",
        },
      },
      sizes: {
        sm: {
          padding: "0.5rem 1rem",
          fontSize: "0.875rem",
          height: "2.5rem",
        },
        md: {
          padding: "0.75rem 1.5rem",
          fontSize: "1rem",
          height: "3rem",
        },
        lg: {
          padding: "1rem 2rem",
          fontSize: "1.125rem",
          height: "3.5rem",
        },
      },
      borderRadius: "0.75rem",
      fontWeight: "600",
      transition: "all 200ms cubic-bezier(0.4, 0, 0.2, 1)",
    },
    link: {
      base: "text-primary font-medium",
      hover: "text-primary/80 underline",
      visited: "text-primary/70",
      underline: false,
      transition: "all 200ms cubic-bezier(0.4, 0, 0.2, 1)",
    },
    card: {
      borderRadius: "1rem",
      boxShadow:
        "0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)",
      padding: "1.5rem",
      borderWidth: "1px",
      borderColor: "border",
    },
    input: {
      borderRadius: "0.5rem",
      borderWidth: "2px",
      borderColor: "border",
      focusBorderColor: "ring",
      padding: "0.625rem 0.875rem",
      fontSize: "1rem",
      transition: "all 200ms cubic-bezier(0.4, 0, 0.2, 1)",
    },
  },
  sections: {
    hero: {
      minHeight: "60vh",
      padding: "4rem 2rem",
      textAlign: "center",
      overlayOpacity: 0.3,
    },
    about: {
      padding: "4rem 2rem",
      maxWidth: "56rem",
      textAlign: "center",
    },
    gallery: {
      padding: "4rem 2rem",
      gridCols: 4,
      gap: "1.5rem",
      aspectRatio: "square",
    },
    contact: {
      padding: "4rem 2rem",
      layout: "centered",
      formWidth: "32rem",
    },
    reviews: {
      padding: "4rem 2rem",
      layout: "carousel",
      itemsPerRow: 1,
    },
  },
};
