export const convexEnv = {

  CLIENT_ORIGIN: process.env.CLIENT_ORIGIN || "*",

  NEXT_PUBLIC_APP_URL:
    process.env.NEXT_PUBLIC_APP_URL || "http://localhost:3000",
  NEXT_PUBLIC_CONVEX_URL: process.env.NEXT_PUBLIC_CONVEX_URL!,
  NEXT_PUBLIC_ROOT_DOMAIN:
    process.env.NEXT_PUBLIC_ROOT_DOMAIN || "locasite.xyz",

  GOOGLE_MAPS_API_KEY: process.env.GOOGLE_MAPS_API_KEY!,
  GOOGLE_BUSINESS_CLIENT_ID: process.env.GOOGLE_BUSINESS_CLIENT_ID!,
  GOOGLE_BUSINESS_CLIENT_SECRET: process.env.GOOGLE_BUSINESS_CLIENT_SECRET!,

  STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY!,
  STRIPE_WEBHOOKS_SECRET: process.env.STRIPE_WEBHOOKS_SECRET!,
  STRIPE_PRICE_PROFESSIONAL: process.env.STRIPE_PRICE_PROFESSIONAL,
  STRIPE_PRICE_BUSINESS: process.env.STRIPE_PRICE_BUSINESS,

  CUSTOM_DOMAIN_CNAME:
    process.env.CUSTOM_DOMAIN_CNAME || "cname.vercel-dns.com",

  VERCEL_API_TOKEN: process.env.VERCEL_API_TOKEN,
  VERCEL_PROJECT_ID: process.env.VERCEL_PROJECT_ID,

  CONVEX_SITE_URL: process.env.CONVEX_SITE_URL || "http://localhost:3000",

  NEXT_PUBLIC_TINYBIRD_API_URL:
    process.env.NEXT_PUBLIC_TINYBIRD_API_URL || "https://api.tinybird.co",
  NEXT_PUBLIC_TINYBIRD_TOKEN: process.env.NEXT_PUBLIC_TINYBIRD_TOKEN!,
} as const;

export type ConvexEnv = typeof convexEnv;
